/**
 * Anthropic Claude API helper for the Doctor Farmer MagicScript Pipeline.
 * High-EQ copywriting stages (6, 9) → claude-sonnet-4-6 (default)
 *
 * Claude is preferred over Gemini for tasks that require:
 * - Warm, conversational spoken-word dialogue (Stage 6)
 * - Complex two-column production script formatting (Stage 8)
 * - Social media hook writing and viral moment extraction (Stage 9)
 *
 * Gemini remains primary for pure data / logic tasks (Stage 7).
 */

export const CLAUDE_MODELS = {
  sonnet: "claude-sonnet-4-6",  // Claude Sonnet 4.6 — faster and cheaper than Opus
};

/**
 * Persona instruction injected into Claude's system prompt for
 * stages that write in Dr. Prabhakar's voice (Stage 6 and Stage 8).
 */
export const DR_PRABHAKAR_PERSONA = `VOICE & PERSONA:
Write as Dr. Prabhakar Raj — a warm, authoritative South Indian lifestyle medicine doctor with 20+ years of clinical experience reversing Type 2 diabetes. His voice is:
- Conversational and direct. Short sentences. No padding.
- High empathy — he speaks to patients as family, not as subjects.
- Honest about uncertainty. Never oversells. Never hypes.
- Grounded in South Indian cultural context — references Tamil Nadu food, festivals, family structures naturally.
BANNED WORDS (never use these): delve, crucial, tapestry, multifaceted, it is worth noting, in conclusion, furthermore, leverage, paradigm, holistic journey, game-changer, groundbreaking, seamlessly, navigate, underscore.
If a sentence sounds like it was generated by an AI writing assistant — rewrite it.`;

/**
 * Robust JSON extractor — identical logic to callGemini's aggressive cleaner.
 * Handles: markdown fences, preamble text, postscript text, partial outputs.
 */
function extractJson(text) {
  // Step 1 — strip markdown fences (```json...``` or ```...```)
  if (text.includes("```")) {
    text = text.replace(/^```(?:json)?\s*/im, "").replace(/```\s*$/im, "");
  }
  text = text.trim();

  // Step 2 — object anchor: slice from first { to last }
  const firstBrace = text.indexOf("{");
  const lastBrace  = text.lastIndexOf("}");
  if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
    text = text.substring(firstBrace, lastBrace + 1);
  } else {
    // Step 2b — array anchor: slice from first [ to last ] (e.g. Stage 9 reels)
    const firstArr = text.indexOf("[");
    const lastArr  = text.lastIndexOf("]");
    if (firstArr !== -1 && lastArr !== -1 && lastArr > firstArr) {
      text = text.substring(firstArr, lastArr + 1);
    }
  }

  if (!text) throw new Error("Claude returned empty text after JSON extraction.");
  return JSON.parse(text);
}

/**
 * Call Anthropic Claude and return either parsed JSON or plain text.
 *
 * @param {string}  apiKey       - Anthropic API key
 * @param {string}  systemPrompt - System / persona instructions
 * @param {string}  userPrompt   - The task prompt
 * @param {boolean} isJson       - true  → strip fences and parse JSON
 *                                 false → return raw text (chat mode)
 * @param {number}  maxTokens    - Max output tokens (default 8192)
 *
 * Auto-retries on 529 (overloaded) and 429 (rate limited) with
 * exponential backoff: 3 s → 6 s → 12 s (same cadence as callGemini).
 */
export async function callClaude(apiKey, systemPrompt, userPrompt, isJson = true, maxTokens = 8192) {
  // Append a JSON fence reminder to the system prompt when in JSON mode
  const finalSystem = isJson
    ? systemPrompt +
      "\n\nCRITICAL OUTPUT RULE: Return ONLY a valid JSON object or array. " +
      "No markdown fences. No explanation before or after the JSON. " +
      "No trailing commas. The very first character of your response must be { or [."
    : systemPrompt;

  const MAX_RETRIES    = 2; // Reduced — fail fast, don't hang 30s on parse errors
  const RETRYABLE_HTTP = new Set([429, 500, 529]);
  let lastError;

  for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
    if (attempt > 0) {
      await new Promise((r) => setTimeout(r, 3000 * Math.pow(2, attempt - 1)));
    }

    let res, data;
    try {
      res  = await fetch("https://api.anthropic.com/v1/messages", {
        method:  "POST",
        headers: {
          "Content-Type":      "application/json",
          "x-api-key":         apiKey,
          "anthropic-version": "2023-06-01",
        },
        body: JSON.stringify({
          model:      CLAUDE_MODELS.sonnet,
          max_tokens: maxTokens,
          system:     finalSystem,
          messages:   [{ role: "user", content: userPrompt }],
        }),
      });
      data = await res.json();
    } catch (networkErr) {
      lastError = new Error(`Network error: ${networkErr.message}`);
      continue;
    }

    // API-level error
    if (data.error) {
      const status  = data.error.status ?? res.status;
      const message = data.error.message ?? JSON.stringify(data.error);
      const httpCode = typeof status === "number" ? status : Number(res.status);

      if (RETRYABLE_HTTP.has(httpCode)) {
        lastError = new Error(`Claude error (${httpCode}): ${message}`);
        continue; // retry on overload / rate-limit
      }
      throw new Error(`Claude error: ${message}`);
    }

    // HTTP-level error without a JSON body error field
    if (!res.ok) {
      if (RETRYABLE_HTTP.has(res.status)) {
        lastError = new Error(`Claude HTTP ${res.status}`);
        continue;
      }
      throw new Error(`Claude HTTP ${res.status}: ${res.statusText}`);
    }

    const rawText  = data.content?.[0]?.text ?? "";
    const stopReason = data.stop_reason ?? "unknown";
    if (stopReason === "max_tokens") {
      console.warn(`[claude] Response truncated — hit max_tokens limit. Length: ${rawText.length} chars. Increase maxTokens.`);
    }
    if (!rawText) {
      lastError = new Error(`Claude returned empty response (stop_reason: ${stopReason}).`);
      if (stopReason === "max_tokens") throw lastError; // not retryable
      continue;
    }

    if (!isJson) return rawText.trim();

    // Parse JSON with full error context logged
    try {
      return extractJson(rawText);
    } catch (parseErr) {
      console.error("[claude] JSON parse failed. Raw excerpt:", rawText.slice(0, 300));
      lastError = new Error(`JSON parse error: ${parseErr.message}`);
      continue; // retry — model may have truncated mid-output
    }
  }

  throw lastError ?? new Error("Claude API failed after maximum retries.");
}
