// Static content type config + context panel data for the Reels Agent

export const CONTENT_TYPES = [
  {
    id: "myth-buster",
    label: "Myth Buster",
    icon: "⚡",
    description: "Destroy a common health belief with science",
    hookStyle: "Confrontational opening question",
    structure: "Claim → Debunk → Science → Reframe",
    tone: "Confident, slightly provocative",
    bestFor: "Topics with widespread misinformation",
    evidenceNeed: "HIGH — requires at least 2 PubMed citations",
    accentColor: "#f59e0b",
    accentBg: "bg-amber-500/10",
    accentBorder: "border-amber-500/30",
    accentGlow: "shadow-amber-500/20",
  },
  {
    id: "problem-reveal",
    label: "Problem Reveal",
    icon: "🔍",
    description: "Expose a hidden health problem — then give the fix. Problem + Solution format.",
    hookStyle: "Alarming statistic or 'you might have this' opener",
    structure: "Hook → Hidden Problem → Why Ignored → The Fix",
    tone: "Urgent, empathetic, solution-focused",
    bestFor: "Subclinical or commonly missed conditions",
    evidenceNeed: "MEDIUM — prevalence data and 1–2 sources",
    accentColor: "#06b6d4",
    accentBg: "bg-cyan-500/10",
    accentBorder: "border-cyan-500/30",
    accentGlow: "shadow-cyan-500/20",
  },
  {
    id: "education-drop",
    label: "Education Drop",
    icon: "🧠",
    description: "Teach one surprising fact in a way they'll never forget",
    hookStyle: "Did you know / surprising stat opener",
    structure: "Hook → Fact 1 → Fact 2 → Counterintuitive reveal → CTA",
    tone: "Confident, authoritative, fast-paced",
    bestFor: "Complex science made simple",
    evidenceNeed: "MEDIUM — key fact must be verifiable",
    accentColor: "#8b5cf6",
    accentBg: "bg-violet-500/10",
    accentBorder: "border-violet-500/30",
    accentGlow: "shadow-violet-500/20",
  },
  {
    id: "faq-explainer",
    label: "FAQ Explainer",
    icon: "❓",
    description: "Answer the #1 question people search about this topic",
    hookStyle: "Direct question that the viewer is already asking",
    structure: "Question → Common wrong answer → Why wrong → Right answer → Source",
    tone: "Helpful, clear, trustworthy",
    bestFor: "High search volume health questions",
    evidenceNeed: "MEDIUM — answer must reference at least one study",
    accentColor: "#22c55e",
    accentBg: "bg-green-500/10",
    accentBorder: "border-green-500/30",
    accentGlow: "shadow-green-500/20",
  },
  {
    id: "contrarian",
    label: "Contrarian / Rebel Reach",
    icon: "🎯",
    description: "Say the unpopular truth that challenges mainstream advice",
    hookStyle: "Direct challenge to a named mainstream belief",
    structure: "Challenge → Expose → Prove → Dare",
    tone: "Bold, slightly provocative, anti-mainstream",
    bestFor: "Contrarian positions that are scientifically defensible",
    evidenceNeed: "HIGH — contrarian claim must have strong backing",
    accentColor: "#f97316",
    accentBg: "bg-orange-500/10",
    accentBorder: "border-orange-500/30",
    accentGlow: "shadow-orange-500/20",
  },
];

export const getContentTypeById = (id) =>
  CONTENT_TYPES.find((t) => t.id === id) || null;
